dev:
	docker compose -f docker-compose.dev.yml up

dev-build:
	docker compose -f docker-compose.dev.yml up --build

down:
	docker compose -f docker-compose.dev.yml down

restart-backend:
	docker compose -f docker-compose.dev.yml restart backend

restart-frontend:
	docker compose -f docker-compose.dev.yml restart frontend